// <auto-generated />
using System;
using Audi100.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Audi100.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Audi100.Models.AuditFinding", b =>
                {
                    b.Property<int>("AuditFindingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditFindingId"));

                    b.Property<int>("AuditReportId")
                        .HasColumnType("int");

                    b.Property<string>("AuthorizedForReport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BasisAudit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CauseAudit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConditionAudit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CriterionAudit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataReport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("DetailFindingAudit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EffectAudit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FindLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FindShortName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FindShortNameId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("FindingTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("NegativeRisk")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NegativeWeighting")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NumberOfFindings")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PlanOfActionAudit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PositiveRisk")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PositiveWeighting")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RequirementOfAudit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeightingClassification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WeightingClassificationId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("WorkExecutedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditFindingId");

                    b.ToTable("AuditFinding");
                });

            modelBuilder.Entity("Audi100.Models.AuditPrint", b =>
                {
                    b.Property<int>("AuditPrintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditPrintId"));

                    b.Property<int>("AuditReportId")
                        .HasColumnType("int");

                    b.Property<string>("AuditorId1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuditorId2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuditorId3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CostSeccionPrint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateE")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateI")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeId1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeId2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeId3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Line")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OtherEmployee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherEmployee2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherEmployee3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherEmployee4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Part1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Part2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Part3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Part4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalPart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditPrintId");

                    b.ToTable("AuditPrint");
                });

            modelBuilder.Entity("Audi100.Models.AuditReport", b =>
                {
                    b.Property<int>("AuditReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditReportId"));

                    b.Property<string>("AuditObservations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuditorId1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuditorId2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuditorId3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bsc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BscId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Classification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClassificationId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreationDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("CrossExcess")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CrossShortage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EmployeeId1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeId2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeId3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Excess")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ExpectedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Hours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("HoursInReviwe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MissingInQ")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OriginOfTheReview")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeriodString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReportDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewPriority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewdateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReviewdateOf")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Shortage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VariationOfHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("nomCompleto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomDepto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomDivision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomSeccion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditReportId");

                    b.ToTable("AuditReport");
                });

            modelBuilder.Entity("Audi100.Models.AuditTrail", b =>
                {
                    b.Property<int>("AuditTrailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditTrailId"));

                    b.Property<int?>("AuditFindingId")
                        .HasColumnType("int");

                    b.Property<int?>("AuditReportId")
                        .HasColumnType("int");

                    b.Property<string>("AuditTrailDepto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuditTrailFollow")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuditTrailSeccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AuditTrailStatus")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("AuditTrailWeighting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("DetailFindingAudit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FindLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FindShortName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Line")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NegativeRisk")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NegativeWeighting")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NumberOfFindings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PositiveRisk")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PositiveWeighting")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReportCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeightingClassification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomDepto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomDivision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomSeccion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditTrailId");

                    b.ToTable("AuditTrail");
                });

            modelBuilder.Entity("Audi100.Models.Bsc", b =>
                {
                    b.Property<int>("BscId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BscId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BscId");

                    b.ToTable("Bsc");
                });

            modelBuilder.Entity("Audi100.Models.Classification", b =>
                {
                    b.Property<int>("ClassificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassificationId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClassificationId");

                    b.ToTable("Classification");
                });

            modelBuilder.Entity("Audi100.Models.Photo", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhotoId"));

                    b.Property<int>("AuditFindingId")
                        .HasColumnType("int");

                    b.Property<byte[]>("BytePdf")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("BytePhone")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("PhotoId");

                    b.ToTable("Photo");
                });

            modelBuilder.Entity("Audi100.Models.ShortF", b =>
                {
                    b.Property<int>("ShortFId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShortFId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShortFId");

                    b.ToTable("ShortF");
                });

            modelBuilder.Entity("Audi100.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserRoleId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Audi100.Models.Weighing", b =>
                {
                    b.Property<int>("WeighingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeighingId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WeighingId");

                    b.ToTable("WeightingClassification");
                });

            modelBuilder.Entity("Audi100.Models.AuditFinding", b =>
                {
                    b.OwnsOne("Audi100.Models.RecordLog", "RecordLog", b1 =>
                        {
                            b1.Property<int>("AuditFindingId")
                                .HasColumnType("int");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasComment("Usuario que creo el registro");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime2")
                                .HasComment("Fecha y hora de creación del registro");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("bit")
                                .HasComment("Registro activo");

                            b1.Property<bool>("IsSystem")
                                .HasColumnType("bit")
                                .HasComment("Es un registro del sistema, los registros del sistema no pueden ser eliminados");

                            b1.Property<string>("ObjectKey")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasComment("Código identificador del objeto representado en el registro");

                            b1.Property<string>("RecordKey")
                                .IsRequired()
                                .HasMaxLength(36)
                                .HasColumnType("nvarchar(36)")
                                .HasComment("Identificador único del registro, asignado en el momento de creación");

                            b1.Property<DateTime>("SyncDate")
                                .HasColumnType("datetime2")
                                .HasComment("Ultima fecha de sincronización");

                            b1.Property<int>("SyncStatus")
                                .HasColumnType("int")
                                .HasComment("Estatus de sincronización del registro");

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasComment("Ultimo usuario que modificó el registro");

                            b1.Property<DateTime>("UpdatedDate")
                                .HasColumnType("datetime2")
                                .HasComment("Ultima fecha y hora de actualización del registro");

                            b1.HasKey("AuditFindingId");

                            b1.ToTable("AuditFinding");

                            b1.WithOwner()
                                .HasForeignKey("AuditFindingId");
                        });

                    b.Navigation("RecordLog");
                });

            modelBuilder.Entity("Audi100.Models.AuditPrint", b =>
                {
                    b.OwnsOne("Audi100.Models.RecordLog", "RecordLog", b1 =>
                        {
                            b1.Property<int>("AuditPrintId")
                                .HasColumnType("int");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasComment("Usuario que creo el registro");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime2")
                                .HasComment("Fecha y hora de creación del registro");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("bit")
                                .HasComment("Registro activo");

                            b1.Property<bool>("IsSystem")
                                .HasColumnType("bit")
                                .HasComment("Es un registro del sistema, los registros del sistema no pueden ser eliminados");

                            b1.Property<string>("ObjectKey")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasComment("Código identificador del objeto representado en el registro");

                            b1.Property<string>("RecordKey")
                                .IsRequired()
                                .HasMaxLength(36)
                                .HasColumnType("nvarchar(36)")
                                .HasComment("Identificador único del registro, asignado en el momento de creación");

                            b1.Property<DateTime>("SyncDate")
                                .HasColumnType("datetime2")
                                .HasComment("Ultima fecha de sincronización");

                            b1.Property<int>("SyncStatus")
                                .HasColumnType("int")
                                .HasComment("Estatus de sincronización del registro");

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasComment("Ultimo usuario que modificó el registro");

                            b1.Property<DateTime>("UpdatedDate")
                                .HasColumnType("datetime2")
                                .HasComment("Ultima fecha y hora de actualización del registro");

                            b1.HasKey("AuditPrintId");

                            b1.ToTable("AuditPrint");

                            b1.WithOwner()
                                .HasForeignKey("AuditPrintId");
                        });

                    b.Navigation("RecordLog");
                });

            modelBuilder.Entity("Audi100.Models.AuditReport", b =>
                {
                    b.OwnsOne("Audi100.Models.RecordLog", "RecordLog", b1 =>
                        {
                            b1.Property<int>("AuditReportId")
                                .HasColumnType("int");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasComment("Usuario que creo el registro");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime2")
                                .HasComment("Fecha y hora de creación del registro");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("bit")
                                .HasComment("Registro activo");

                            b1.Property<bool>("IsSystem")
                                .HasColumnType("bit")
                                .HasComment("Es un registro del sistema, los registros del sistema no pueden ser eliminados");

                            b1.Property<string>("ObjectKey")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasComment("Código identificador del objeto representado en el registro");

                            b1.Property<string>("RecordKey")
                                .IsRequired()
                                .HasMaxLength(36)
                                .HasColumnType("nvarchar(36)")
                                .HasComment("Identificador único del registro, asignado en el momento de creación");

                            b1.Property<DateTime>("SyncDate")
                                .HasColumnType("datetime2")
                                .HasComment("Ultima fecha de sincronización");

                            b1.Property<int>("SyncStatus")
                                .HasColumnType("int")
                                .HasComment("Estatus de sincronización del registro");

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasComment("Ultimo usuario que modificó el registro");

                            b1.Property<DateTime>("UpdatedDate")
                                .HasColumnType("datetime2")
                                .HasComment("Ultima fecha y hora de actualización del registro");

                            b1.HasKey("AuditReportId");

                            b1.ToTable("AuditReport");

                            b1.WithOwner()
                                .HasForeignKey("AuditReportId");
                        });

                    b.Navigation("RecordLog");
                });

            modelBuilder.Entity("Audi100.Models.AuditTrail", b =>
                {
                    b.OwnsOne("Audi100.Models.RecordLog", "RecordLog", b1 =>
                        {
                            b1.Property<int>("AuditTrailId")
                                .HasColumnType("int");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasComment("Usuario que creo el registro");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime2")
                                .HasComment("Fecha y hora de creación del registro");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("bit")
                                .HasComment("Registro activo");

                            b1.Property<bool>("IsSystem")
                                .HasColumnType("bit")
                                .HasComment("Es un registro del sistema, los registros del sistema no pueden ser eliminados");

                            b1.Property<string>("ObjectKey")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasComment("Código identificador del objeto representado en el registro");

                            b1.Property<string>("RecordKey")
                                .IsRequired()
                                .HasMaxLength(36)
                                .HasColumnType("nvarchar(36)")
                                .HasComment("Identificador único del registro, asignado en el momento de creación");

                            b1.Property<DateTime>("SyncDate")
                                .HasColumnType("datetime2")
                                .HasComment("Ultima fecha de sincronización");

                            b1.Property<int>("SyncStatus")
                                .HasColumnType("int")
                                .HasComment("Estatus de sincronización del registro");

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasComment("Ultimo usuario que modificó el registro");

                            b1.Property<DateTime>("UpdatedDate")
                                .HasColumnType("datetime2")
                                .HasComment("Ultima fecha y hora de actualización del registro");

                            b1.HasKey("AuditTrailId");

                            b1.ToTable("AuditTrail");

                            b1.WithOwner()
                                .HasForeignKey("AuditTrailId");
                        });

                    b.Navigation("RecordLog");
                });

            modelBuilder.Entity("Audi100.Models.Bsc", b =>
                {
                    b.OwnsOne("Audi100.Models.RecordLog", "RecordLog", b1 =>
                        {
                            b1.Property<int>("BscId")
                                .HasColumnType("int");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasComment("Usuario que creo el registro");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime2")
                                .HasComment("Fecha y hora de creación del registro");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("bit")
                                .HasComment("Registro activo");

                            b1.Property<bool>("IsSystem")
                                .HasColumnType("bit")
                                .HasComment("Es un registro del sistema, los registros del sistema no pueden ser eliminados");

                            b1.Property<string>("ObjectKey")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasComment("Código identificador del objeto representado en el registro");

                            b1.Property<string>("RecordKey")
                                .IsRequired()
                                .HasMaxLength(36)
                                .HasColumnType("nvarchar(36)")
                                .HasComment("Identificador único del registro, asignado en el momento de creación");

                            b1.Property<DateTime>("SyncDate")
                                .HasColumnType("datetime2")
                                .HasComment("Ultima fecha de sincronización");

                            b1.Property<int>("SyncStatus")
                                .HasColumnType("int")
                                .HasComment("Estatus de sincronización del registro");

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasComment("Ultimo usuario que modificó el registro");

                            b1.Property<DateTime>("UpdatedDate")
                                .HasColumnType("datetime2")
                                .HasComment("Ultima fecha y hora de actualización del registro");

                            b1.HasKey("BscId");

                            b1.ToTable("Bsc");

                            b1.WithOwner()
                                .HasForeignKey("BscId");
                        });

                    b.Navigation("RecordLog");
                });

            modelBuilder.Entity("Audi100.Models.Classification", b =>
                {
                    b.OwnsOne("Audi100.Models.RecordLog", "RecordLog", b1 =>
                        {
                            b1.Property<int>("ClassificationId")
                                .HasColumnType("int");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasComment("Usuario que creo el registro");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime2")
                                .HasComment("Fecha y hora de creación del registro");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("bit")
                                .HasComment("Registro activo");

                            b1.Property<bool>("IsSystem")
                                .HasColumnType("bit")
                                .HasComment("Es un registro del sistema, los registros del sistema no pueden ser eliminados");

                            b1.Property<string>("ObjectKey")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasComment("Código identificador del objeto representado en el registro");

                            b1.Property<string>("RecordKey")
                                .IsRequired()
                                .HasMaxLength(36)
                                .HasColumnType("nvarchar(36)")
                                .HasComment("Identificador único del registro, asignado en el momento de creación");

                            b1.Property<DateTime>("SyncDate")
                                .HasColumnType("datetime2")
                                .HasComment("Ultima fecha de sincronización");

                            b1.Property<int>("SyncStatus")
                                .HasColumnType("int")
                                .HasComment("Estatus de sincronización del registro");

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasComment("Ultimo usuario que modificó el registro");

                            b1.Property<DateTime>("UpdatedDate")
                                .HasColumnType("datetime2")
                                .HasComment("Ultima fecha y hora de actualización del registro");

                            b1.HasKey("ClassificationId");

                            b1.ToTable("Classification");

                            b1.WithOwner()
                                .HasForeignKey("ClassificationId");
                        });

                    b.Navigation("RecordLog");
                });

            modelBuilder.Entity("Audi100.Models.Photo", b =>
                {
                    b.OwnsOne("Audi100.Models.RecordLog", "RecordLog", b1 =>
                        {
                            b1.Property<int>("PhotoId")
                                .HasColumnType("int");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasComment("Usuario que creo el registro");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime2")
                                .HasComment("Fecha y hora de creación del registro");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("bit")
                                .HasComment("Registro activo");

                            b1.Property<bool>("IsSystem")
                                .HasColumnType("bit")
                                .HasComment("Es un registro del sistema, los registros del sistema no pueden ser eliminados");

                            b1.Property<string>("ObjectKey")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasComment("Código identificador del objeto representado en el registro");

                            b1.Property<string>("RecordKey")
                                .IsRequired()
                                .HasMaxLength(36)
                                .HasColumnType("nvarchar(36)")
                                .HasComment("Identificador único del registro, asignado en el momento de creación");

                            b1.Property<DateTime>("SyncDate")
                                .HasColumnType("datetime2")
                                .HasComment("Ultima fecha de sincronización");

                            b1.Property<int>("SyncStatus")
                                .HasColumnType("int")
                                .HasComment("Estatus de sincronización del registro");

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasComment("Ultimo usuario que modificó el registro");

                            b1.Property<DateTime>("UpdatedDate")
                                .HasColumnType("datetime2")
                                .HasComment("Ultima fecha y hora de actualización del registro");

                            b1.HasKey("PhotoId");

                            b1.ToTable("Photo");

                            b1.WithOwner()
                                .HasForeignKey("PhotoId");
                        });

                    b.Navigation("RecordLog");
                });

            modelBuilder.Entity("Audi100.Models.ShortF", b =>
                {
                    b.OwnsOne("Audi100.Models.RecordLog", "RecordLog", b1 =>
                        {
                            b1.Property<int>("ShortFId")
                                .HasColumnType("int");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasComment("Usuario que creo el registro");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime2")
                                .HasComment("Fecha y hora de creación del registro");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("bit")
                                .HasComment("Registro activo");

                            b1.Property<bool>("IsSystem")
                                .HasColumnType("bit")
                                .HasComment("Es un registro del sistema, los registros del sistema no pueden ser eliminados");

                            b1.Property<string>("ObjectKey")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasComment("Código identificador del objeto representado en el registro");

                            b1.Property<string>("RecordKey")
                                .IsRequired()
                                .HasMaxLength(36)
                                .HasColumnType("nvarchar(36)")
                                .HasComment("Identificador único del registro, asignado en el momento de creación");

                            b1.Property<DateTime>("SyncDate")
                                .HasColumnType("datetime2")
                                .HasComment("Ultima fecha de sincronización");

                            b1.Property<int>("SyncStatus")
                                .HasColumnType("int")
                                .HasComment("Estatus de sincronización del registro");

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasComment("Ultimo usuario que modificó el registro");

                            b1.Property<DateTime>("UpdatedDate")
                                .HasColumnType("datetime2")
                                .HasComment("Ultima fecha y hora de actualización del registro");

                            b1.HasKey("ShortFId");

                            b1.ToTable("ShortF");

                            b1.WithOwner()
                                .HasForeignKey("ShortFId");
                        });

                    b.Navigation("RecordLog");
                });

            modelBuilder.Entity("Audi100.Models.User", b =>
                {
                    b.OwnsOne("Audi100.Models.RecordLog", "RecordLog", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasComment("Usuario que creo el registro");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime2")
                                .HasComment("Fecha y hora de creación del registro");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("bit")
                                .HasComment("Registro activo");

                            b1.Property<bool>("IsSystem")
                                .HasColumnType("bit")
                                .HasComment("Es un registro del sistema, los registros del sistema no pueden ser eliminados");

                            b1.Property<string>("ObjectKey")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasComment("Código identificador del objeto representado en el registro");

                            b1.Property<string>("RecordKey")
                                .IsRequired()
                                .HasMaxLength(36)
                                .HasColumnType("nvarchar(36)")
                                .HasComment("Identificador único del registro, asignado en el momento de creación");

                            b1.Property<DateTime>("SyncDate")
                                .HasColumnType("datetime2")
                                .HasComment("Ultima fecha de sincronización");

                            b1.Property<int>("SyncStatus")
                                .HasColumnType("int")
                                .HasComment("Estatus de sincronización del registro");

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasComment("Ultimo usuario que modificó el registro");

                            b1.Property<DateTime>("UpdatedDate")
                                .HasColumnType("datetime2")
                                .HasComment("Ultima fecha y hora de actualización del registro");

                            b1.HasKey("UserId");

                            b1.ToTable("User");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("RecordLog");
                });

            modelBuilder.Entity("Audi100.Models.Weighing", b =>
                {
                    b.OwnsOne("Audi100.Models.RecordLog", "RecordLog", b1 =>
                        {
                            b1.Property<int>("WeighingId")
                                .HasColumnType("int");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasComment("Usuario que creo el registro");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime2")
                                .HasComment("Fecha y hora de creación del registro");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("bit")
                                .HasComment("Registro activo");

                            b1.Property<bool>("IsSystem")
                                .HasColumnType("bit")
                                .HasComment("Es un registro del sistema, los registros del sistema no pueden ser eliminados");

                            b1.Property<string>("ObjectKey")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasComment("Código identificador del objeto representado en el registro");

                            b1.Property<string>("RecordKey")
                                .IsRequired()
                                .HasMaxLength(36)
                                .HasColumnType("nvarchar(36)")
                                .HasComment("Identificador único del registro, asignado en el momento de creación");

                            b1.Property<DateTime>("SyncDate")
                                .HasColumnType("datetime2")
                                .HasComment("Ultima fecha de sincronización");

                            b1.Property<int>("SyncStatus")
                                .HasColumnType("int")
                                .HasComment("Estatus de sincronización del registro");

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasComment("Ultimo usuario que modificó el registro");

                            b1.Property<DateTime>("UpdatedDate")
                                .HasColumnType("datetime2")
                                .HasComment("Ultima fecha y hora de actualización del registro");

                            b1.HasKey("WeighingId");

                            b1.ToTable("WeightingClassification");

                            b1.WithOwner()
                                .HasForeignKey("WeighingId");
                        });

                    b.Navigation("RecordLog");
                });
#pragma warning restore 612, 618
        }
    }
}
